# Generated by Django 5.0.6 on 2024-06-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='items_supplied',
            new_name='items_they_supply',
        ),
    ]
