# Generated by Django 5.0.6 on 2024-06-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_items_supplied_supplier_items_they_supply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeinventory',
            options={'verbose_name_plural': 'Store inventories'},
        ),
        migrations.AddField(
            model_name='supplier',
            name='items_supplied',
            field=models.ManyToManyField(related_name='supplied_items', through='api.StoreInventory', to='api.item'),
        ),
    ]
