# Generated by Django 5.0.6 on 2024-06-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_storeinventory_options_supplier_items_supplied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='items_supplied',
        ),
    ]
